
parameters:
    routes:
        homepage-no-version:
            method: GET
            path: '/'
            controller: '@Loopia\App\Controllers\RedirectToVersion'
        homepage:
            method: GET
            path: '/v1/'
            controller: '@Loopia\App\Controllers\Homepage'
        details:
            method: GET
            path: '/v1/item/{id:\d+}'
            controller: '@Loopia\App\Controllers\FilmDetails'

